// Generated by @orbit/drizzle from schema.ts — do not edit by hand.
// Re-run `orbit-drizzle generate` to update.

import {
  createSchema,
  relationships,
  table,
  string,
  number,
  json,
  optional,
} from "@zeronsh/orbit/client";
import type { RowOf } from "@zeronsh/orbit/client";
import type { PostSettings } from "./db/schema";

const comment = table("comment")
  .columns({
    id: string(),
    post_id: string(),
    author_id: string(),
    body: string(),
  })
  .primaryKey("id");

const post = table("post")
  .columns({
    id: string(),
    author_id: string(),
    title: string(),
    body: string(),
    status: string<"draft" | "published" | "archived">(),
    views: optional(number()),
    settings: optional(json<PostSettings>()),
  })
  .primaryKey("id");

const post_tag = table("post_tag")
  .columns({
    post_id: string(),
    tag_id: string(),
  })
  .primaryKey("post_id", "tag_id");

const tag = table("tag")
  .columns({
    id: string(),
    label: string(),
  })
  .primaryKey("id");

const user = table("user")
  .columns({
    id: string(),
    email: string<`${string}@${string}`>(),
    name: string(),
    bio: optional(string()),
    created_at: optional(number()),
  })
  .primaryKey("id");

export const schema = createSchema({
  tables: [comment, post, post_tag, tag, user],
  relationships: [
  relationships(comment, ({ one, many }) => ({
      post: one({ sourceField: ["post_id"], destField: ["id"], destSchema: post }),
      author: one({ sourceField: ["author_id"], destField: ["id"], destSchema: user }),
  })),
  relationships(post, ({ one, many }) => ({
      author: one({ sourceField: ["author_id"], destField: ["id"], destSchema: user }),
      comments: many({ sourceField: ["id"], destField: ["post_id"], destSchema: comment }),
      tags: many(
        { sourceField: ["id"], destField: ["post_id"], destSchema: post_tag },
        { sourceField: ["tag_id"], destField: ["id"], destSchema: tag },
      ),
  })),
  relationships(tag, ({ one, many }) => ({
      posts: many(
        { sourceField: ["id"], destField: ["tag_id"], destSchema: post_tag },
        { sourceField: ["post_id"], destField: ["id"], destSchema: post },
      ),
  })),
  relationships(user, ({ one, many }) => ({
      posts: many({ sourceField: ["id"], destField: ["author_id"], destSchema: post }),
      comments: many({ sourceField: ["id"], destField: ["author_id"], destSchema: comment }),
  })),
  ],
});

export type Schema = typeof schema;

export type Comment = RowOf<typeof comment>;
export type Post = RowOf<typeof post>;
export type PostTag = RowOf<typeof post_tag>;
export type Tag = RowOf<typeof tag>;
export type User = RowOf<typeof user>;
