// The `orbit-drizzle generate` pipeline:
//   import schema (runtime) → resolve custom types (ts-morph) → IR → emit → write.

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { pathToFileURL } from 'node:url';
import { getTableColumns, getTableName, is, Table } from 'drizzle-orm';
import { emitSchema } from '../../../orm-core/src/index.ts';
import { drizzleToIR, type DrizzleAdapterConfig } from '../introspect.ts';
import { orbitTypeOf, type DrizzleColumnLike } from '../type-map.ts';
import { resolveCustomTypes, type ResolveTable } from './type-resolution.ts';

export interface GenerateOptions {
  /** Path to the Drizzle schema module (a single `.ts` file exporting tables + relations). */
  readonly schemaPath: string;
  /** Output path. Default `./orbit-schema.gen.ts`. */
  readonly outputPath?: string;
  /** tsconfig for type resolution + module resolution. */
  readonly tsConfigPath?: string;
  /** Run Prettier over the output if available. */
  readonly format?: boolean;
  /** Append `.js` to relative imports (Node16/NodeNext ESM). */
  readonly jsExtension?: boolean;
  /** Module the Orbit schema helpers are imported from. Default `@orbit/client`. */
  readonly importFrom?: string;
  /** Exported schema const name. Default `schema`. */
  readonly schemaName?: string;
  /** Table/column selection (see {@link DrizzleAdapterConfig.tables}). */
  readonly tables?: DrizzleAdapterConfig['tables'];
  readonly debug?: boolean;
}

export interface GenerateResult {
  readonly outputPath: string;
  readonly source: string;
}

/** Generate an Orbit schema source file from a Drizzle schema. */
export async function generate(options: GenerateOptions): Promise<GenerateResult> {
  const schemaModulePath = path.resolve(options.schemaPath);
  const outputPath = path.resolve(options.outputPath ?? './orbit-schema.gen.ts');

  // 1. Load the schema module at runtime (tables + relations).
  const moduleObj = (await import(pathToFileURL(schemaModulePath).href)) as Record<string, unknown>;

  // 2. Collect per-table resolution metadata (export name, jsKey ↔ dbName).
  const resolveTables: ResolveTable[] = [];
  for (const [exportName, value] of Object.entries(moduleObj)) {
    if (!is(value, Table)) continue;
    const table = value as Table;
    const tableName = getTableName(table);
    if (options.tables && options.tables[tableName] === false) continue;
    const cols = getTableColumns(table) as Record<string, DrizzleColumnLike & { name: string }>;
    const columns = Object.entries(cols)
      .map(([jsKey, col]) => {
        const base = orbitTypeOf(col);
        return base ? { jsKey, dbName: col.name, baseType: base } : null;
      })
      .filter((c): c is NonNullable<typeof c> => c !== null);
    resolveTables.push({ exportName, tableName, columns });
  }

  // 3. Resolve custom `$type<>()` / enum types via the TypeScript compiler.
  const { customTypes, typeImports } = await resolveCustomTypes(resolveTables, {
    schemaModulePath,
    outputFilePath: outputPath,
    tsConfigFilePath: options.tsConfigPath,
    jsExtension: options.jsExtension,
  });

  // 4. Build the IR with the resolved custom types folded in.
  const ir = drizzleToIR(moduleObj, { customTypes, tables: options.tables, debug: options.debug });

  // 5. Emit the Orbit schema source.
  let source = emitSchema(ir, {
    importFrom: options.importFrom ?? '@zeronsh/orbit/client',
    schemaName: options.schemaName,
    jsExtension: options.jsExtension,
    typeImports,
    header: [
      `Generated by @orbit/drizzle from ${path.basename(schemaModulePath)} — do not edit by hand.`,
      `Re-run \`orbit-drizzle generate\` to update.`,
    ],
  });

  // 6. Optional Prettier.
  if (options.format) source = await formatWithPrettier(source, outputPath);

  await fs.writeFile(outputPath, source, 'utf8');
  return { outputPath, source };
}

async function formatWithPrettier(source: string, filepath: string): Promise<string> {
  try {
    const prettier = await import('prettier');
    const config = (await prettier.resolveConfig(filepath)) ?? {};
    return prettier.format(source, { ...config, parser: 'typescript' });
  } catch {
    console.warn('⚠️  orbit-drizzle: prettier not found — skipping formatting.');
    return source;
  }
}
