// Generated by @orbit/drizzle from schema.ts — do not edit by hand.
// Re-run `orbit-drizzle generate` to update.

import {
  createSchema,
  table,
  string,
  number,
  optional,
} from "@zeronsh/orbit/client";
import type { RowOf } from "@zeronsh/orbit/client";

const cursor = table("cursor")
  .columns({
    id: string(),
    x: number(),
    y: number(),
    color: string<`#${string}`>(),
    size: number(),
    erasing: optional(number<0 | 1>()),
    updated: number(),
  })
  .primaryKey("id");

const pixel = table("pixel")
  .columns({
    id: string(),
    x: number(),
    y: number(),
    color: string<`#${string}`>(),
    updated: number(),
  })
  .primaryKey("id");

export const schema = createSchema({
  tables: [cursor, pixel],
});

export type Schema = typeof schema;

export type Cursor = RowOf<typeof cursor>;
export type Pixel = RowOf<typeof pixel>;
